package GUI;
import database.database;
import java.sql.ResultSet;
import javax.swing.*;
import kereta2.JadwalKereta;
import GUI.TambahKereta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Silva_Jen_Retno
 */
public class DataKereta extends javax.swing.JFrame {
    private database db;
    public int id;
    
    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tabeljadwalkereta.getModel();
       model.setRowCount(0); // Mengosongkan tabel
       model.setColumnIdentifiers(new Object[]{"ID Kereta", "Nama Kereta", "Tipe", "Rute", "Jarak", "Stasiun", "Waktu Berangkat", "Waktu Tiba", "ID Admin", "ID Karyawan"});

       try {
            database db = new database();
            db.openConnection();
            db.statement = db.connection.createStatement();
           
            String query = "SELECT * FROM jadwalkereta";
            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                id = resultSet.getInt("Id_Kereta");
                String nama = resultSet.getString("Nama_Kereta");
                String tipe = resultSet.getString("Tipe_Kereta");
                String rute = resultSet.getString("Rute");
                String jarak = resultSet.getString("Jarak");
                String stasiun = resultSet.getString("Stasiun");
                String waktuberangkat = resultSet.getString("Waktu_Keberangkatan");
                String waktudatang = resultSet.getString("Waktu_Kedatangan");
                String tanggal = resultSet.getString("Tanggal");
                String idadmin = resultSet.getString("ADMIN_ID_User");
                String idkaryawan = resultSet.getString("Karyawan_Id_Karyawan");
                model.addRow(new Object[]{id, nama, tipe, rute, jarak, stasiun, waktuberangkat, waktudatang, tanggal, idadmin, idkaryawan});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        } 
    }
    
    public DataKereta() throws ClassNotFoundException, SQLException {
        
        initComponents();
        populateTable();
        db = new database();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeljadwalkereta = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DATA PENJADWALAN KERETA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, 30));

        tabeljadwalkereta.setBackground(new java.awt.Color(255, 210, 66));
        tabeljadwalkereta.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        tabeljadwalkereta.setForeground(new java.awt.Color(0, 0, 0));
        tabeljadwalkereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Tipe ", "Rute", "Jarak", "Stasiun", "Waktu Berangkat", "Waktu Tiba", "Tanggal", "ID Admin", "ID Karyawan"
            }
        ));
        jScrollPane1.setViewportView(tabeljadwalkereta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 660, 240));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/menutampil (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        
        String Id_Kereta = JOptionPane.showInputDialog("Masukan ID : ", null);

//        // Validasi input, pastikan ID yang akan dihapus tidak kosong
        if (Id_Kereta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // Buat objek jadwal kereta
        JadwalKereta datakereta = new JadwalKereta();
        datakereta.Id_Kereta = Integer.parseInt(Id_Kereta);
        datakereta.delete();
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
            TambahKereta tambahKereta = new TambahKereta();
            tambahKereta.setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DataKereta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabeljadwalkereta;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables

   
}
